version: '2'
services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - moddle-network
  php:
    image: php:8-fpm
    volumes:
      - .:/var/www/html
    networks:
      - moddle-network
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MoodleRoot
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleroot
    networks:
      - moddle-network

  moodle:
    image: erseco/alpine-moodle
    build: .
    restart: unless-stopped
    environment:
      - LANG=pt_BR.UTF-8
      - SITE_URL=http://localhost
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=moodleroot
      - DB_PASS=MoodleRoot
      - DB_PREFIX=mdl_
      - MOODLE_LANGUAGE=pt_br
      - MOODLE_SITENAME=SESI-MT
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=PLEASE_CHANGEME
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[moodle]
    ports:
      - 80:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - mysql
      - nginx

volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
