version: '2'
services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - moddle-network

  php:
    image: php:8-fpm
    volumes:
      - .:/var/www/html
    networks:
      - moddle-network

  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MoodleRoot
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleroot
    networks:
      - moddle-network
    volumes:
      - mysql-data:/var/lib/mysql

  moodle:
    image: erseco/alpine-moodle
    build: .
    restart: unless-stopped
    environment:
      - LANG=pt_BR.UTF-8
      - SITE_URL=http://localhost
      - DB_TYPE=mysql  # Corrigido para MySQL
      - DB_HOST=mysql  # Corrigido para mysql
      - DB_PORT=3306  # Corrigido para a porta do MySQL
      - DB_NAME=moodle
      - DB_USER=moodleroot
      - DB_PASS=MoodleRoot
      - DB_PREFIX=mdl_
      - MOODLE_LANGUAGE=pt_br
      - MOODLE_SITENAME=SESI-MT
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=PLEASE_CHANGEME
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[moodle]
    volumes:
      - moodle-data:/var/www/moodledata
      - moodle-html:/var/www/html
    depends_on:
      - mysql
      - nginx
    networks:
      - moddle-network

networks:
  moddle-network:

volumes:
  mysql-data:
  moodle-data:
  moodle-html:
