version: '3.8'

services:

  moodle-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: moodle_pass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle_pass
    volumes:
      - vol-db:/var/lib/mysql

  moodle-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: moodle:4.2
    ports:
      - "9090:80"
    environment:
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle_user
      MOODLE_DATABASE_PASSWORD: moodle_pass
      MOODLE_DATABASE_HOST: moodle-db
    volumes:
      - vol-appdata:/var/www/moodledata
      - vol-app:/var/www/html

volumes:
  vol-db:
  vol-appdata:
  vol-app:
